#!/usr/bin/env python3
 
# Python program to create lists
# Name : Tervil Moywaywa
# Email : tervilmoywaywa@gmail.com
# Date : 22nd Feb 2023
# File : continue.py
num = 0

while(num < 10):
    num = num + 1
    print(num)
    if(num == 5):
        print("count has reached five")
        continue
        
    
    
