#design a logo
print("_________________________________")
print("|           TERV                 |")
print("|           HOLDINGS             |")
print("|           LIMITED              |")
print("|                                |")
print("|                                |")
print("|                                |")
print("|            EST                 |")
print("|                                |")
print("|            2000                |")
print("__________________________________")
