#write a program that displays a big T
print("============================")
print("             ||             ")
print("             ||             ")
print("             ||             ")
print("             ||             ")
print("             ||             ")
print("             ||             ")
print("             ||             ")
print("             ||             ")