f_num = input ("Enter first number")
s_num = input("Enter second number")
#convert the string into integer
sum_num = int(f_num)+int(s_num)
print("the sum of the two numbers is",sum_num)
diff_num=int(f_num)-int(s_num)
print("the difference of the two numbers is",diff_num)
prod_num=int(f_num)*int(s_num)
print("the product of the two numbers is",prod_num)
quot_num=int(f_num)/int(s_num)
print("the quotient of the two numbers is",quot_num)
